<a href="https://colab.research.google.com/github/kurnya/221230002-Pengantar-ML/blob/main/Week2/Praktikum_4_Tensor_Dimas_Kurniawan_221230002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)
bias = torch.randn(1)


In [ ]:
# SOLUSI 1: Implementasi linear layer manual
def linear_layer(X, W, b):
    return torch.matmul(X, W) + b

output = linear_layer(X, weights, bias)
print("Linear output shape:", output.shape)
# SOLUSI 1: Implementasi linear layer manual
def linear_layer(X, W, b):
    return torch.matmul(X, W) + b

output = linear_layer(X, weights, bias)
print("Linear output shape:", output.shape)


Linear output shape: torch.Size([32, 1])
Linear output shape: torch.Size([32, 1])


In [ ]:
# SOLUSI 2: Implementasi ReLU
def relu_activation(tensor):
    return torch.maximum(tensor, torch.tensor(0.0))

activated = relu_activation(output)
print("ReLU output shape:", activated.shape)


ReLU output shape: torch.Size([32, 1])


In [ ]:
# SOLUSI 3: Batch Normalization sederhana
def simple_batch_norm(tensor, epsilon=1e-5):
    mean = torch.mean(tensor, dim=0, keepdim=True)
    std = torch.std(tensor, dim=0, keepdim=True)
    return (tensor - mean) / (std + epsilon)

normalized = simple_batch_norm(X)
print("Batch norm output shape:", normalized.shape)


Batch norm output shape: torch.Size([32, 10])


In [ ]:
# SOLUSI 4: One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    batch_size = labels.shape[0]
    one_hot = torch.zeros(batch_size, num_classes)
    one_hot[torch.arange(batch_size), labels] = 1
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)

print("Labels:", labels)
print("One-hot encoding:\n", one_hot)


Labels: tensor([1, 2, 2, 0, 1, 0, 1, 1, 2, 0])
One-hot encoding:
 tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


In [ ]:
# BONUS: Implementasi perkalian matriks manual
def manual_matrix_multiply(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    if cols_A != rows_B:
        raise ValueError("Matrix dimensions mismatch")

    result = torch.zeros(rows_A, cols_B)
    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i, j] += A[i, k] * B[k, j]
    return result

A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

print("Manual:\n", manual_result)
print("Torch:\n", torch_result)


Manual:
 tensor([[19., 22.],
        [43., 50.]])
Torch:
 tensor([[19., 22.],
        [43., 50.]])


In [ ]:
# EXTRA: Operasi tensor untuk image processing
batch_images = torch.randn(4, 3, 32, 32)

reshaped = batch_images.reshape(4, 3, 1024)
permuted = batch_images.permute(0, 2, 3, 1)

print("Original:", batch_images.shape)
print("Reshaped:", reshaped.shape)
print("Permuted:", permuted.shape)

def simple_conv2d(input_tensor, kernel_size=3):
    patches = input_tensor.unfold(2, kernel_size, 1).unfold(3, kernel_size, 1)
    print("Patches shape:", patches.shape)
    return patches

patches = simple_conv2d(batch_images)


Original: torch.Size([4, 3, 32, 32])
Reshaped: torch.Size([4, 3, 1024])
Permuted: torch.Size([4, 32, 32, 3])
Patches shape: torch.Size([4, 3, 30, 30, 3, 3])


In [ ]:
# TEST ASSERTIONS
assert output.shape == (batch_size, 1)
assert torch.all(activated >= 0)
assert normalized.shape == X.shape
assert one_hot.shape == (10, 3)
assert torch.allclose(manual_result, torch_result)

print("\n✅ Semua assertions berhasil! Solusi benar.")



✅ Semua assertions berhasil! Solusi benar.
